### ISSUE TITLE
needs javascript example

### ISSUE THREAD

**Issue by Radisovik** [cretz/pb-and-k#4] opened 2018-07-25 03:18 UTC
I've been trying to get a working javascript example that I could contribute.  However my javascript/browser skills are sub-par.  So I'm filing this issue in hopes that someone else will be able to help out.  :) 

pbandk-runtime-js.js:11401 Uncaught ReferenceError: module is not defined
    at pbandk-runtime-js.js:11401
(anonymous) @ pbandk-runtime-js.js:11401

That line reads:
}(module.exports, require('kotlin'), require('protobufjs/light')));

It feels like the library is required to run in a node.js environment

**Comment by Radisovik** [comment] 2018-07-25 03:51
I see both kotlin.js and protobuf.js (from the light distro) coming down the wire. (via network tab in chrome).  They show up before pbandk-runtime-js.js.   I stuck a console.log in kotlin.js and protobuf.js so I could confirm they were being started..

Kotlin is loaded
Proto buf is loaded
pbandk-runtime-js.js:11402 Uncaught ReferenceError: module is not defined
    at pbandk-runtime-js.js:11402

It must be something simple with javascript and modules to which I'm ignorant --  but figuring out what I'm ignorant about is proving frustrating..:)

**Comment by cretz** [comment] 2018-12-27 21:43
@Radisovik - I know this is an old issue and you may not need it anymore, but I have put an example in master. Feedback appreciated. I'll close this on next release.

**Comment by Radisovik** [comment] 2018-12-27 21:50
Thanks for the heads up.. I'll go check it out.  I ended up putting off my serialization woes and just using JSON until I could get pb and k working within my build.  My problems center around the fact that I'm not using any sort of module system.  (I think).  I'll go check out your example and see!

**Comment by Radisovik** [comment] 2018-12-27 21:51
I had also not been using kotlin-frontend-plugin  since it wasn't up to date with Kotlin 1.3.0.. but now it is!

**Comment by cretz** [comment] 2018-12-27 22:45
You don't need a `settings.gradle` file for a single project named the same as the directory. How are you running this and what gradle version are you using?

**Comment by Radisovik** [comment] 2018-12-27 22:47
I'm on gradle 5.0 -- is pb and k still only working with 4.7?  (oh how I miss the gradle wrapper! :)  ) I'm just changing to the examples/browser-js directory and typing "gradle build"

**Comment by cretz** [comment] 2018-12-27 22:49
Haven't tried with 5 I don't think, latest 4.x is what I was using (oh how annoying it would be to now have checked in the gradle wrapper 4 times for 3 examples and the root and make sure to upgrade them all each gradle update :-) ).

I will try and get back to you.

**Comment by Radisovik** [comment] 2018-12-27 23:04
I went back to 4.7 and it got farther.  I am now down to:

> * What went wrong:
Execution failed for task ':generateProto'.
> Codegen plugin kotlin not defined

Was going to check the path to the batch -- but getting pulled away by the kids.  Will check back later.

**Comment by cretz** [comment] 2018-12-27 23:07
@Radisovik - Yeah, I'm getting that too strangely even with `protoc-gen-kotlin` on the PATH. May have to be hand-set, checking...

**Comment by cretz** [comment] 2018-12-27 23:16
Ok, I confirmed this is caused by 0.8.6 in https://github.com/google/protobuf-gradle-plugin and fixed in 0.8.7. Updating all examples...

**Comment by cretz** [comment] 2018-12-27 23:32
Ok, Gradle 5 does require a local settings.gradle file (completely empty is fine) or it looks up parent paths which I don't like but meh. So I can touch a few files. However, Kotlin frontend plugin has problems. I opened up an issue at #13.

Let me know if this now works for you w/ Gradle 4.x.

**Comment by Radisovik** [comment] 2019-01-05 19:12
In the example -- it looks like addressbook.kt is generated *after* compiling the kotlin code?
To illustrate -- if I remove addressbook.kt -- I get compile failures -- because Web.kt depends on it. But shouldn't the code generator kicked in and created it before the kotlin compiler?  (I know this is a nuance.. and one might argue that is okay... as long as you always check your generated files into source control... but if that is the intent its something that should be documented)

**Comment by cretz** [comment] 2019-01-05 22:50
@Radisovik - it is a personal preference of mine to check in the generated code and generate manually. But I admit it's not the most common. I can change it (I think I have to just reenable compileJava and add that file to gitignore), will do it next week.

**Comment by cretz** [comment] 2019-01-07 21:55
@Radisovik - Take a peek at my recent commit. I just added the task as a dependency of the `compileKotlin2Js` task. Is the example reasonable now?

**Comment by Radisovik** [comment] 2019-01-07 22:19
Looks good to me.

**Closed** 2019-01-07 23:09 UTC
Labels: fixed-in-master
